/* Lumina Trails - playable prototype (core) */
const config = { type: Phaser.AUTO, parent:'game', width:960, height:640, backgroundColor:'#07121a', physics:{default:'arcade', arcade:{gravity:{y:0},debug:false}}, scene:{preload:preload, create:create, update:update} };
let game = new Phaser.Game(config);
function preload(){ this.load.image('player','assets/player_skin_default.png'); this.load.image('enemy','assets/enemy_orb.png'); this.load.image('crystal','assets/crystal_blue.png'); this.load.image('banner','assets/banner.png'); this.load.audio('sfx_pickup','assets/sfx_pickup.wav'); this.load.audio('music_loop','assets/music_loop.wav'); }
let player, cursors, enemies, crystals, inRun=false, runTimer=0, crystalsCollected=0, logEl;
function create(){ logEl=document.getElementById('log'); this.add.image(480,70,'banner'); player=this.physics.add.sprite(480,320,'player').setCollideWorldBounds(true); player.speed=160; enemies=this.physics.add.group(); crystals=this.physics.add.group(); cursors=this.input.keyboard.createCursorKeys(); this.physics.add.overlap(player, crystals, collectCrystal, null, this); this.physics.add.overlap(player, enemies, hitEnemy, null, this); document.getElementById('btn-start').addEventListener('click', ()=>{ if(!inRun) startRun(this); }); appendLog('Prototype ready'); try{ this.sound.add('music_loop',{loop:true,volume:0.2}).play(); }catch(e){} }
function update(time,delta){ if(!player) return; let vx=0, vy=0; if(cursors.left.isDown) vx=-1; else if(cursors.right.isDown) vx=1; if(cursors.up.isDown) vy=-1; else if(cursors.down.isDown) vy=1; player.setVelocity(vx*player.speed, vy*player.speed); if(inRun){ runTimer -= delta/1000; if(runTimer<=0) endRun(); } enemies.getChildren().forEach(e=>{ let dist=Phaser.Math.Distance.Between(player.x,player.y,e.x,e.y); if(dist<220) this.physics.moveToObject(e,player,e.speed); else { e.x += Math.cos(this.time.now/1000+e._off)*0.5; e.y += Math.sin(this.time.now/1000+e._off)*0.5; } }, this); }
function startRun(scene){ inRun=true; crystalsCollected=0; runTimer=90; spawnEntities(scene,8,10); appendLog('Run started'); }
function spawnEntities(scene, enemCount, cryCount){ enemies.clear(true,true); crystals.clear(true,true); for(let i=0;i<enemCount;i++){ let x=Phaser.Math.Between(60,900); let y=Phaser.Math.Between(140,580); let e=enemies.create(x,y,'enemy'); e.hp=10+Phaser.Math.Between(0,20); e.speed=40+Phaser.Math.Between(0,40); e._off=Math.random()*10; } for(let i=0;i<cryCount;i++){ let x=Phaser.Math.Between(80,880); let y=Phaser.Math.Between(160,560); crystals.create(x,y,'crystal').setImmovable(true); } }
function collectCrystal(p,c){ c.destroy(); crystalsCollected++; appendLog('Collected crystal'); try{ this.scene.scene.sound.play('sfx_pickup'); }catch(e){} }
function hitEnemy(p,e){ e.hp -= 10; appendLog('Hit enemy'); if(e.hp<=0){ e.destroy(); crystalsCollected++; appendLog('Enemy defeated'); } }
function endRun(){ inRun=false; appendLog('Run ended. Collected '+crystalsCollected+' crystals'); }
function appendLog(t){ let el=document.createElement('div'); el.textContent='['+new Date().toLocaleTimeString()+'] '+t; logEl.prepend(el); }
